export const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  selectRole: "/select-role",
  admin: {
    dashboard: "/admin/dashboard",
    batches: "/admin/batches",
    faculty: "/admin/faculty",
    students: "/admin/students",
    parents: "/admin/parents",
    courses: "/admin/courses",
    marketplace: "/admin/marketplace",
    certificates: "/admin/certificates",
    payments: "/admin/payments",
    attendance: "/admin/attendance",
    announcements: "/admin/announcements",
    settings: "/admin/settings",
  },
  faculty: {
    dashboard: "/faculty/dashboard",
    courses: "/faculty/courses",
    batches: "/faculty/batches",
    students: "/faculty/students",
    assignments: "/faculty/assignments",
    attendance: "/faculty/attendance",
    live: "/faculty/live",
    messages: "/faculty/messages",
    calendar: "/faculty/calendar",
    settings: "/faculty/settings",
  },
  student: {
    dashboard: "/student/dashboard",
    courses: "/student/courses",
    learningPath: "/student/learning-path",
    aiStudy: "/student/ai-study-assistance",
    marketplace: "/student/marketplace",
    assignments: "/student/assignments",
    attendance: "/student/attendance",
    certificates: "/student/certificates",
    community: "/student/community",
    messages: "/student/messages",
    live: "/student/live",
    calendar: "/student/calendar",
    profile: "/student/profile",
    settings: "/student/settings",
  },
  parent: {
    dashboard: "/parent/dashboard",
    children: "/parent/children",
    performance: "/parent/performance",
    attendance: "/parent/attendance",
    fees: "/parent/fees",
    certificates: "/parent/certificates",
    messages: "/parent/messages",
    notifications: "/parent/notifications",
    profile: "/parent/profile",
    settings: "/parent/settings",
  },
} as const;

export function roleDashboardPath(role: string) {
  return `/${role.toLowerCase()}/dashboard`;
}
